/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module "vue-router/auto-resolver" {
  export type ParamParserCustom = never;
}

declare module "vue-router/auto-routes" {
  import type { RouteRecordInfo, ParamValue } from "vue-router";

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    "/": RouteRecordInfo<
      "/",
      "/",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/about/": RouteRecordInfo<
      "/about/",
      "/about",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/ai/style-fusion/": RouteRecordInfo<
      "/ai/style-fusion/",
      "/ai/style-fusion",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/ai/text2image/": RouteRecordInfo<
      "/ai/text2image/",
      "/ai/text2image",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/gallery/": RouteRecordInfo<
      "/gallery/",
      "/gallery",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/inheritor/[id]": RouteRecordInfo<
      "/inheritor/[id]",
      "/inheritor/:id",
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >;
    "/inheritors/": RouteRecordInfo<
      "/inheritors/",
      "/inheritors",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/introduction/": RouteRecordInfo<
      "/introduction/",
      "/introduction",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/news/": RouteRecordInfo<
      "/news/",
      "/news",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/news/[id]": RouteRecordInfo<
      "/news/[id]",
      "/news/:id",
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      never
    >;
    "/privacy-policy/": RouteRecordInfo<
      "/privacy-policy/",
      "/privacy-policy",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/reserve/": RouteRecordInfo<
      "/reserve/",
      "/reserve",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/shop/": RouteRecordInfo<
      "/shop/",
      "/shop",
      Record<never, never>,
      Record<never, never>,
      never
    >;
    "/terms-of-use/": RouteRecordInfo<
      "/terms-of-use/",
      "/terms-of-use",
      Record<never, never>,
      Record<never, never>,
      never
    >;
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    "src/pages/index.vue": {
      routes: "/";
      views: never;
    };
    "src/pages/about/index.vue": {
      routes: "/about/";
      views: never;
    };
    "src/pages/ai/style-fusion/index.vue": {
      routes: "/ai/style-fusion/";
      views: never;
    };
    "src/pages/ai/text2image/index.vue": {
      routes: "/ai/text2image/";
      views: never;
    };
    "src/pages/gallery/index.vue": {
      routes: "/gallery/";
      views: never;
    };
    "src/pages/inheritor/[id].vue": {
      routes: "/inheritor/[id]";
      views: never;
    };
    "src/pages/inheritors/index.vue": {
      routes: "/inheritors/";
      views: never;
    };
    "src/pages/introduction/index.vue": {
      routes: "/introduction/";
      views: never;
    };
    "src/pages/news/index.vue": {
      routes: "/news/";
      views: never;
    };
    "src/pages/news/[id].vue": {
      routes: "/news/[id]";
      views: never;
    };
    "src/pages/privacy-policy/index.vue": {
      routes: "/privacy-policy/";
      views: never;
    };
    "src/pages/reserve/index.vue": {
      routes: "/reserve/";
      views: never;
    };
    "src/pages/shop/index.vue": {
      routes: "/shop/";
      views: never;
    };
    "src/pages/terms-of-use/index.vue": {
      routes: "/terms-of-use/";
      views: never;
    };
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info["routes"]
      : keyof RouteNamedMap;
}
